In [11]:
struct Atom{T}
    attype::String
    name::String
    resnum::Int
    resname::String
    charge::T
    mass::T
    σ::T
    ϵ::T
end

In [12]:
using StaticArrays

In [13]:
function Atom(;
                attype="",
                name="",
                resnum=0,
                resname="",
                charge=0.0,
                mass=0.0,
                σ=0.0,
                ϵ=0.0)
    return Atom{typeof(mass)}(attype, name, resnum, resname, charge, mass, σ, ϵ)
end

function Base.show(io::IO, a::Atom)
    print(io, "Atom{", typeof(a.charge), "} with name \"", a.name,
                "\", type \"", a.attype, "\", charge=", a.charge, ", mass=",
                a.mass, ", σ=", a.σ, ", ϵ=", a.ϵ)
end

In [14]:
n_atoms2 = 100
mass2 = 1.0
atoms2 = [Atom(mass=mass2, σ=1.0, ϵ=1.0) for i in 1:50]
atoms3 = [Atom(name="$i" ,mass=mass2, σ=2.0, ϵ=3.0) for i in 50:n_atoms2]
box_size2 = 30.0 # nm
coords2 = [box_size2 .* rand(SVector{2}) for i in 1:n_atoms2]

100-element Array{SArray{Tuple{2},Float64,1,2},1}:
 [15.06687007923083, 1.4626398121807482]
 [28.76104965928692, 24.4167912224356]
 [3.745763433911642, 26.27141173736835]
 [0.7429928840410827, 19.373115307762404]
 [2.772361758578854, 14.606363968375828]
 [15.755168936626445, 14.715505381725446]
 [4.873193840248781, 23.366511844117195]
 [9.236615408730364, 3.0018927616276403]
 [3.059680944756611, 12.484551711698483]
 [8.691490660291352, 19.572183003870148]
 [19.572293988577538, 26.86884859306393]
 [13.818204009202095, 27.044904107765426]
 [23.690514247877005, 1.4707793170880001]
 ⋮
 [1.8452158042693179, 16.29179364601346]
 [25.722099925849893, 9.256680069428544]
 [12.00295025778427, 20.87850813304203]
 [28.74407180308397, 28.79491796490693]
 [9.353213673756777, 3.395417370680076]
 [5.5493934162512515, 27.617060737522994]
 [27.503274398913593, 14.639214888911932]
 [26.929719712891597, 9.338486754018788]
 [19.577830938180405, 14.133063385137747]
 [22.399177032886328, 9.821582389050242]
 [

In [15]:
coords3 = [box_size2 .* [rand(),rand()] for i in 1:2]

2-element Array{Array{Float64,1},1}:
 [25.52791994917397, 9.927041424752169]
 [17.5588620822477, 23.79464741855533]

In [5]:
function Átomo(m,c,vx,vy,n)
    ListaM = zeros(n,1)
    ListaC = zeros(n,1)
    ListaVx = zeros(n,1)
    ListaVy = zeros(n,1)
    for i in 1:n
        ListaM[i]=m
        ListaC[i]=c
        ListaVx[i]=vx
        ListaVy[i]=vy
    end 
    return ListaM, ListaVx, ListaVy
end

Átomo (generic function with 1 method)

In [6]:
Átomo(1,0,0,1,2)

([1.0; 1.0], [0.0; 0.0], [1.0; 1.0])

In [84]:

n=2
m=4
Arro = [Neo for i in 1:m]
#for i in 1:m 
    #MatrizPrueba=Arro[i]
    #for j in 1:n
        #for k in 1:n
            #MatrizPrueba[j,k]=10
        #end
    #end
#end
#println(Arro)

4-element Array{Array{Array{Float64,1},2},1}:
 [[0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; … ; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]]
 [[0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; … ; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]]
 [[0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; … ; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]]
 [[0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; … ; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]]

In [72]:
m1 = zeros(n,n)
for i in 1:n
    for j in 1:n
        m1[i,j] = 1
    end
end
display(m1)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [83]:
arx = zeros(10)
ary = zeros(10)
Neo = [[x,y] for x in arx, y in ary]
display(Neo)

10×10 Array{Array{Float64,1},2}:
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]  …  [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]  …  [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]

In [7]:
using LinearAlgebra

In [78]:
function Átomo(m,c,vx,vy,n)
    ListaM = zeros(n,1)
    ListaC = zeros(n,1)
    ListaVx = zeros(n,1)
    ListaVy = zeros(n,1)
    for i in 1:n
        ListaM[i]=m
        ListaC[i]=c
        ListaVx[i]=vx
        ListaVy[i]=vy
    end 
    return ListaM, ListaVx, ListaVy
end

Átomo (generic function with 1 method)

In [82]:
Atomito = Átomo(1,0,0,1,2)

([1.0; 1.0], [0.0; 0.0], [1.0; 1.0])

In [84]:
Atomito[1][2]

1.0

In [16]:
coords3 = [box_size2 .* [rand(),rand()] for i in 1:2]

2-element Array{Array{Float64,1},1}:
 [0.5327977878890389, 2.774680486405572]
 [9.102302232231045, 13.057506628024614]

In [32]:
coords3[1][2,1]
coords3[2]-coords3[1]

2-element Array{Float64,1}:
  8.569504444342005
 10.282826141619042

In [63]:
function distancia()
    x_1 = coords3[1][1]
    x_2 = coords3[2][1]
    y_1 = coords3[1][2]
    y_2 = coords3[2][2]
    return sqrt((x_1-x_2)^2+(y_1-y_2)^2)
end
dist = distancia()

function LennardForce(ϵ, σ)
    return ((24.0*σ)/dist)*(2.0*(ϵ/dist)^(12)-(ϵ/dist)^(6))*((coords3[2]-coords3[1]))
end

function LaGravedadNoEsUnaFuerza()
    Judas = -(1)*(9.81)*coords3[1][2]
    return [coords3[1][1],Judas]
end

LaGravedadNoEsUnaFuerza (generic function with 1 method)

In [58]:
typeof(distancia())

Float64

In [70]:
PruebaLennard = LennardForce(1.0,1.0)

2-element Array{Float64,1}:
 -2.6712436319860725e-6
 -3.2053118156389333e-6

In [72]:
NewtonTerra = LaGravedadNoEsUnaFuerza()

2-element Array{Float64,1}:
   0.5327977878890389
 -27.219615571638663

In [76]:
FuerzaTotal = PruebaLennard+NewtonTerra
display(FuerzaTotal)

2-element Array{Float64,1}:
   0.5327951166454069
 -27.21961877695048

In [86]:
function VerletBásica()
    return R_k_1 = coords3[1] + [Atomito[2][1], Atomito[3][1]]*(0.001) + (1/2)*FuerzaTotal*(0.001)^2
end

VerletBásica (generic function with 1 method)

In [88]:
R_k_co = VerletBásica()

2-element Array{Float64,1}:
 0.5327980542865972
 2.7756668765961834

In [ ]:
function distancia2()
    x_1 = coords3[1][1]
    x_2 = coords3[2][1]
    y_1 = coords3[1][2]
    y_2 = coords3[2][2]
    return sqrt((x_1-x_2)^2+(y_1-y_2)^2)
end
dist = distancia()

function LennardForce(ϵ, σ)
    return ((24.0*σ)/dist)*(2.0*(ϵ/dist)^(12)-(ϵ/dist)^(6))*((coords3[2]-coords3[1]))
end

function LaGravedadNoEsUnaFuerza()
    Judas = -(1)*(9.81)*coords3[1][2]
    return [coords3[1][1],Judas]
end