In [1]:
struct Atom{T}
    attype::String
    name::String
    resnum::Int
    resname::String
    charge::T
    mass::T
    σ::T
    ϵ::T
end

In [2]:
using StaticArrays

In [3]:
function Atom(;
                attype="",
                name="",
                resnum=0,
                resname="",
                charge=0.0,
                mass=0.0,
                σ=0.0,
                ϵ=0.0)
    return Atom{typeof(mass)}(attype, name, resnum, resname, charge, mass, σ, ϵ)
end

function Base.show(io::IO, a::Atom)
    print(io, "Atom{", typeof(a.charge), "} with name \"", a.name,
                "\", type \"", a.attype, "\", charge=", a.charge, ", mass=",
                a.mass, ", σ=", a.σ, ", ϵ=", a.ϵ)
end

In [4]:
n_atoms2 = 100
mass2 = 1.0
atoms2 = [Atom(mass=mass2, σ=1.0, ϵ=1.0) for i in 1:50]
atoms3 = [Atom(name="$i" ,mass=mass2, σ=2.0, ϵ=3.0) for i in 50:n_atoms2]
box_size2 = 30.0 # nm
coords2 = [box_size2 .* rand(SVector{2}) for i in 1:n_atoms2]

100-element Array{SArray{Tuple{2},Float64,1,2},1}:
 [0.4106306291240691, 19.85118491213938]
 [11.655278590016211, 8.055339134496265]
 [20.26710714493744, 17.391137754947458]
 [4.1848529898343845, 25.276398248170587]
 [15.289933650359819, 5.310311026774583]
 [2.9877717208876575, 24.001320687427295]
 [10.503275075028938, 9.15040833168928]
 [5.4360872205450805, 16.216270063208743]
 [9.987683965788293, 17.425781128740404]
 [3.3740537641438317, 3.4962310435065747]
 [15.778350198983333, 0.6685221428272281]
 [27.934450532994052, 27.94680998430816]
 [15.646458046579161, 28.466459169139792]
 ⋮
 [20.689970842591393, 7.12564919588192]
 [2.8507096133968424, 18.18236245133859]
 [15.166032743313416, 18.66823418503009]
 [5.322068305670067, 9.681972253095331]
 [18.621008605524295, 1.2159282159787788]
 [11.532352449451807, 29.94299126705474]
 [6.126857002948731, 8.738161046917378]
 [6.260843835891259, 12.133342589114706]
 [14.64236206200437, 3.5736272648496215]
 [7.309275088584187, 19.79514361367756]
 

In [6]:
coords3 = [box_size2 .* [rand(),rand()] for i in 1:n_atoms2]

100-element Array{Array{Float64,1},1}:
 [29.032325884595437, 0.18453453254266838]
 [1.5939541103872812, 5.5696241311830486]
 [16.143740772980046, 22.738564578535083]
 [29.314358960400185, 8.530250937448361]
 [16.713722275986758, 3.540444055949481]
 [26.61240082033253, 27.402337540608283]
 [20.378503670248822, 1.7229195105166517]
 [24.0179722012535, 29.52663239404746]
 [15.718805362080818, 26.904913602353183]
 [2.046653217852037, 2.7313465988804486]
 [7.008898335831644, 2.064319343023544]
 [0.6518534798922815, 23.783938964210204]
 [4.865850876267601, 28.26389832039949]
 ⋮
 [22.253287584217734, 24.486138350511474]
 [18.38094693787815, 29.393885331251838]
 [5.920916025761331, 23.76875104237358]
 [8.113416290251923, 20.775198421829216]
 [21.989052644015715, 5.650002393411226]
 [16.07828339408521, 8.394291451346405]
 [10.573421435305075, 15.319246773299806]
 [13.940896834716941, 20.809605543675595]
 [5.618226832803794, 27.716554700190933]
 [18.785379073097282, 15.145480096362009]
 [27.33142

In [66]:
function Átomo(m,c,vx,vy)
    ListaM = zeros(100,1)
    ListaC = zeros(100,1)
    ListaVx = zeros(100,1)
    ListaVy = zeros(100,1)
    for i in 1:100
        ListaM[i]=m
        ListaC[i]=c
        ListaVx[i]=vx
        ListaVy[i]=vy
    end 
    return ListaVx, ListaVy
end

Átomo (generic function with 2 methods)

In [67]:
Átomo(1,0,0,1)

([0.0; 0.0; … ; 0.0; 0.0], [1.0; 1.0; … ; 1.0; 1.0])

In [84]:

n=2
m=4
Arro = [Neo for i in 1:m]
#for i in 1:m 
    #MatrizPrueba=Arro[i]
    #for j in 1:n
        #for k in 1:n
            #MatrizPrueba[j,k]=10
        #end
    #end
#end
#println(Arro)

4-element Array{Array{Array{Float64,1},2},1}:
 [[0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; … ; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]]
 [[0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; … ; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]]
 [[0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; … ; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]]
 [[0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; … ; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]; [0.0, 0.0] [0.0, 0.0] … [0.0, 0.0] [0.0, 0.0]]

In [72]:
m1 = zeros(n,n)
for i in 1:n
    for j in 1:n
        m1[i,j] = 1
    end
end
display(m1)

2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

In [83]:
arx = zeros(10)
ary = zeros(10)
Neo = [[x,y] for x in arx, y in ary]
display(Neo)

10×10 Array{Array{Float64,1},2}:
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]  …  [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]  …  [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]
 [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]     [0.0, 0.0]  [0.0, 0.0]  [0.0, 0.0]